sudo: required
dist: trusty

script:
  - bundle exec rake test_app
  - bundle exec rake spec

env:
  - DB=mysql
  - DB=postgres

language: ruby

rvm:
  - 2.5.3
  - 2.4.5

matrix:
    allow_failures:
          - gemfile: gemfiles/spree_master.gemfile

gemfile:
  - gemfiles/spree_3_2.gemfile
  - gemfiles/spree_3_3.gemfile
  - gemfiles/spree_3_5.gemfile
  - gemfiles/spree_3_6.gemfile
  - gemfiles/spree_master.gemfile

before_install:
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"
